<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEhhcQIo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEhhcQIo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEhhcQIo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEhhcQIo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEhhcQIo\App_KernelDevDebugContainer([
    'container.build_hash' => 'EhhcQIo',
    'container.build_id' => '45650f31',
    'container.build_time' => 1711557684,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEhhcQIo');
