<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG93gFFQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG93gFFQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG93gFFQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG93gFFQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG93gFFQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'G93gFFQ',
    'container.build_id' => '3a37e195',
    'container.build_time' => 1706372806,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG93gFFQ');
