<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNmb2Q9u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNmb2Q9u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNmb2Q9u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNmb2Q9u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNmb2Q9u\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nmb2Q9u',
    'container.build_id' => '932dad33',
    'container.build_time' => 1708033099,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNmb2Q9u');
